### ISSUE TITLE
aw snap on chrome 83 when rendering a new document

### ISSUE THREAD

**Issue by kapouer** [pageboard/client#146]
https://bugs.chromium.org/p/chromium/issues/detail?id=1087375

work around:
https://github.com/pageboard/client/commit/20cf8aafd1aaea29fa02a2beaaacbb24073c3200

available as @pageboard/site@0.8.35, @pageboard/elements@0.6.40.

**Comment by jsbastien** [comment]
Merci bien Jérémy, ça fonctionne bien vu d'ici, plus de problème !

Le jeu. 28 mai 2020 à 15:07, Jérémy Lal <notifications@github.com> a écrit :
>
> https://bugs.chromium.org/p/chromium/issues/detail?id=1087375
>
> work around:
> 20cf8aa
>
> available as @pageboard/site@0.8.35, @pageboard/elements@0.6.40.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.



-- 
bastien bouju
EDA s.a.r.l.
T : 09 54 20 99 60 / 06 07 18 25 60
