### ISSUE TITLE
reveal video in carousel breaks autoplay when page has been prerendered

### ISSUE THREAD

**Issue by kapouer** [pageboard/client#156]
See e.g. https://groupe-dfm2.pageboard.io/

**Comment by jsbastien** [comment]
(Ne fonctionne plus car ça marchait très bien)

**Comment by kapouer** [comment]
Not a bug !

Autoplay policy is the culprit here:
https://www.blog.google/products/chrome/improving-autoplay-chrome/

Summary:
- if the user interacted with the page, autoplay works
- else **the video has to be muted** for it to always work
- if the user often plays videos, the website is whitelisted and autoplay will work (for that user)
- if we're making the next youtube, it will become eventually whitelisted by default
